// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: s3.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	S3_ListBuckets_FullMethodName             = "/S3/ListBuckets"
	S3_CreateBucket_FullMethodName            = "/S3/CreateBucket"
	S3_DeleteBucket_FullMethodName            = "/S3/DeleteBucket"
	S3_GetBucket_FullMethodName               = "/S3/GetBucket"
	S3_GetObjectMeta_FullMethodName           = "/S3/GetObjectMeta"
	S3_UpdateObjectMeta_FullMethodName        = "/S3/UpdateObjectMeta"
	S3_ListObjects_FullMethodName             = "/S3/ListObjects"
	S3_CountObjects_FullMethodName            = "/S3/CountObjects"
	S3_PutObject_FullMethodName               = "/S3/PutObject"
	S3_UpdateObject_FullMethodName            = "/S3/UpdateObject"
	S3_GetObject_FullMethodName               = "/S3/GetObject"
	S3_DeleteObject_FullMethodName            = "/S3/DeleteObject"
	S3_GetTierMap_FullMethodName              = "/S3/GetTierMap"
	S3_UpdateObjMeta_FullMethodName           = "/S3/UpdateObjMeta"
	S3_GetStorageClasses_FullMethodName       = "/S3/GetStorageClasses"
	S3_GetBackendTypeByTier_FullMethodName    = "/S3/GetBackendTypeByTier"
	S3_DeleteBucketLifecycle_FullMethodName   = "/S3/DeleteBucketLifecycle"
	S3_PutBucketLifecycle_FullMethodName      = "/S3/PutBucketLifecycle"
	S3_GetBucketLifecycle_FullMethodName      = "/S3/GetBucketLifecycle"
	S3_ListBucketLifecycle_FullMethodName     = "/S3/ListBucketLifecycle"
	S3_UpdateBucket_FullMethodName            = "/S3/UpdateBucket"
	S3_ListBucketUploadRecords_FullMethodName = "/S3/ListBucketUploadRecords"
	S3_InitMultipartUpload_FullMethodName     = "/S3/InitMultipartUpload"
	S3_AbortMultipartUpload_FullMethodName    = "/S3/AbortMultipartUpload"
	S3_CompleteMultipartUpload_FullMethodName = "/S3/CompleteMultipartUpload"
	S3_UploadPart_FullMethodName              = "/S3/UploadPart"
	S3_ListObjectParts_FullMethodName         = "/S3/ListObjectParts"
	S3_AppendObject_FullMethodName            = "/S3/AppendObject"
	S3_PostObject_FullMethodName              = "/S3/PostObject"
	S3_AddUploadRecord_FullMethodName         = "/S3/AddUploadRecord"
	S3_DeleteUploadRecord_FullMethodName      = "/S3/DeleteUploadRecord"
	S3_HeadObject_FullMethodName              = "/S3/HeadObject"
	S3_MoveObject_FullMethodName              = "/S3/MoveObject"
	S3_CopyObject_FullMethodName              = "/S3/CopyObject"
	S3_CopyObjPart_FullMethodName             = "/S3/CopyObjPart"
	S3_PutObjACL_FullMethodName               = "/S3/PutObjACL"
	S3_GetObjACL_FullMethodName               = "/S3/GetObjACL"
	S3_GetBucketLocation_FullMethodName       = "/S3/GetBucketLocation"
	S3_GetBucketVersioning_FullMethodName     = "/S3/GetBucketVersioning"
	S3_PutBucketACL_FullMethodName            = "/S3/PutBucketACL"
	S3_GetBucketACL_FullMethodName            = "/S3/GetBucketACL"
	S3_PutBucketCORS_FullMethodName           = "/S3/PutBucketCORS"
	S3_GetBucketCORS_FullMethodName           = "/S3/GetBucketCORS"
	S3_DeleteBucketCORS_FullMethodName        = "/S3/DeleteBucketCORS"
	S3_PutBucketPolicy_FullMethodName         = "/S3/PutBucketPolicy"
	S3_GetBucketPolicy_FullMethodName         = "/S3/GetBucketPolicy"
	S3_DeleteBucketPolicy_FullMethodName      = "/S3/DeleteBucketPolicy"
	S3_HeadBucket_FullMethodName              = "/S3/HeadBucket"
	S3_RestoreObject_FullMethodName           = "/S3/RestoreObject"
	S3_BackendCheck_FullMethodName            = "/S3/BackendCheck"
)

// S3Client is the client API for S3 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type S3Client interface {
	ListBuckets(ctx context.Context, in *ListBucketsRequest, opts ...grpc.CallOption) (*ListBucketsResponse, error)
	CreateBucket(ctx context.Context, in *Bucket, opts ...grpc.CallOption) (*Bucket, error)
	DeleteBucket(ctx context.Context, in *Bucket, opts ...grpc.CallOption) (*BaseResponse, error)
	GetBucket(ctx context.Context, in *Bucket, opts ...grpc.CallOption) (*GetBucketResponse, error)
	GetObjectMeta(ctx context.Context, in *GetObjectMetaRequest, opts ...grpc.CallOption) (*GetObjectMetaResult, error)
	UpdateObjectMeta(ctx context.Context, in *Object, opts ...grpc.CallOption) (*PutObjectResponse, error)
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
	CountObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*CountObjectsResponse, error)
	PutObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutDataStream, PutObjectResponse], error)
	UpdateObject(ctx context.Context, in *Object, opts ...grpc.CallOption) (*BaseResponse, error)
	GetObject(ctx context.Context, in *GetObjectInput, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectResponse], error)
	DeleteObject(ctx context.Context, in *DeleteObjectInput, opts ...grpc.CallOption) (*DeleteObjectOutput, error)
	GetTierMap(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*GetTierMapResponse, error)
	UpdateObjMeta(ctx context.Context, in *UpdateObjMetaRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetStorageClasses(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*GetStorageClassesResponse, error)
	GetBackendTypeByTier(ctx context.Context, in *GetBackendTypeByTierRequest, opts ...grpc.CallOption) (*GetBackendTypeByTierResponse, error)
	DeleteBucketLifecycle(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	PutBucketLifecycle(ctx context.Context, in *PutBucketLifecycleRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetBucketLifecycle(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*GetBucketLifecycleResponse, error)
	ListBucketLifecycle(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*ListBucketsResponse, error)
	UpdateBucket(ctx context.Context, in *Bucket, opts ...grpc.CallOption) (*BaseResponse, error)
	ListBucketUploadRecords(ctx context.Context, in *ListBucketUploadRequest, opts ...grpc.CallOption) (*ListBucketUploadResponse, error)
	InitMultipartUpload(ctx context.Context, in *InitMultiPartRequest, opts ...grpc.CallOption) (*InitMultiPartResponse, error)
	AbortMultipartUpload(ctx context.Context, in *AbortMultipartRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartRequest, opts ...grpc.CallOption) (*CompleteMultipartResponse, error)
	UploadPart(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutDataStream, UploadPartResponse], error)
	ListObjectParts(ctx context.Context, in *ListObjectPartsRequest, opts ...grpc.CallOption) (*ListObjectPartsResponse, error)
	AppendObject(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	PostObject(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	// For lifecycle, may need some change.
	AddUploadRecord(ctx context.Context, in *MultipartUploadRecord, opts ...grpc.CallOption) (*BaseResponse, error)
	DeleteUploadRecord(ctx context.Context, in *MultipartUploadRecord, opts ...grpc.CallOption) (*BaseResponse, error)
	HeadObject(ctx context.Context, in *BaseObjRequest, opts ...grpc.CallOption) (*Object, error)
	MoveObject(ctx context.Context, in *MoveObjectRequest, opts ...grpc.CallOption) (*MoveObjectResponse, error)
	CopyObject(ctx context.Context, in *CopyObjectRequest, opts ...grpc.CallOption) (*CopyObjectResponse, error)
	CopyObjPart(ctx context.Context, in *CopyObjPartRequest, opts ...grpc.CallOption) (*CopyObjPartResponse, error)
	PutObjACL(ctx context.Context, in *PutObjACLRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetObjACL(ctx context.Context, in *BaseObjRequest, opts ...grpc.CallOption) (*ObjACL, error)
	GetBucketLocation(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetBucketVersioning(ctx context.Context, in *BaseBucketRequest, opts ...grpc.CallOption) (*BucketVersioning, error)
	PutBucketACL(ctx context.Context, in *PutBucketACLRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetBucketACL(ctx context.Context, in *BaseBucketRequest, opts ...grpc.CallOption) (*BucketACL, error)
	PutBucketCORS(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetBucketCORS(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	DeleteBucketCORS(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	PutBucketPolicy(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetBucketPolicy(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	DeleteBucketPolicy(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	HeadBucket(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*Bucket, error)
	RestoreObject(ctx context.Context, in *RestoreObjectRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	BackendCheck(ctx context.Context, in *BackendDetailS3, opts ...grpc.CallOption) (*BaseResponse, error)
}

type s3Client struct {
	cc grpc.ClientConnInterface
}

func NewS3Client(cc grpc.ClientConnInterface) S3Client {
	return &s3Client{cc}
}

func (c *s3Client) ListBuckets(ctx context.Context, in *ListBucketsRequest, opts ...grpc.CallOption) (*ListBucketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBucketsResponse)
	err := c.cc.Invoke(ctx, S3_ListBuckets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) CreateBucket(ctx context.Context, in *Bucket, opts ...grpc.CallOption) (*Bucket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bucket)
	err := c.cc.Invoke(ctx, S3_CreateBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) DeleteBucket(ctx context.Context, in *Bucket, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_DeleteBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetBucket(ctx context.Context, in *Bucket, opts ...grpc.CallOption) (*GetBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketResponse)
	err := c.cc.Invoke(ctx, S3_GetBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetObjectMeta(ctx context.Context, in *GetObjectMetaRequest, opts ...grpc.CallOption) (*GetObjectMetaResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectMetaResult)
	err := c.cc.Invoke(ctx, S3_GetObjectMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) UpdateObjectMeta(ctx context.Context, in *Object, opts ...grpc.CallOption) (*PutObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutObjectResponse)
	err := c.cc.Invoke(ctx, S3_UpdateObjectMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, S3_ListObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) CountObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*CountObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountObjectsResponse)
	err := c.cc.Invoke(ctx, S3_CountObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) PutObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutDataStream, PutObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &S3_ServiceDesc.Streams[0], S3_PutObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutDataStream, PutObjectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S3_PutObjectClient = grpc.ClientStreamingClient[PutDataStream, PutObjectResponse]

func (c *s3Client) UpdateObject(ctx context.Context, in *Object, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_UpdateObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetObject(ctx context.Context, in *GetObjectInput, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &S3_ServiceDesc.Streams[1], S3_GetObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetObjectInput, GetObjectResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S3_GetObjectClient = grpc.ServerStreamingClient[GetObjectResponse]

func (c *s3Client) DeleteObject(ctx context.Context, in *DeleteObjectInput, opts ...grpc.CallOption) (*DeleteObjectOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectOutput)
	err := c.cc.Invoke(ctx, S3_DeleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetTierMap(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*GetTierMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTierMapResponse)
	err := c.cc.Invoke(ctx, S3_GetTierMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) UpdateObjMeta(ctx context.Context, in *UpdateObjMetaRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_UpdateObjMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetStorageClasses(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*GetStorageClassesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStorageClassesResponse)
	err := c.cc.Invoke(ctx, S3_GetStorageClasses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetBackendTypeByTier(ctx context.Context, in *GetBackendTypeByTierRequest, opts ...grpc.CallOption) (*GetBackendTypeByTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBackendTypeByTierResponse)
	err := c.cc.Invoke(ctx, S3_GetBackendTypeByTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) DeleteBucketLifecycle(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_DeleteBucketLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) PutBucketLifecycle(ctx context.Context, in *PutBucketLifecycleRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_PutBucketLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetBucketLifecycle(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*GetBucketLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketLifecycleResponse)
	err := c.cc.Invoke(ctx, S3_GetBucketLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) ListBucketLifecycle(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*ListBucketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBucketsResponse)
	err := c.cc.Invoke(ctx, S3_ListBucketLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) UpdateBucket(ctx context.Context, in *Bucket, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_UpdateBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) ListBucketUploadRecords(ctx context.Context, in *ListBucketUploadRequest, opts ...grpc.CallOption) (*ListBucketUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBucketUploadResponse)
	err := c.cc.Invoke(ctx, S3_ListBucketUploadRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) InitMultipartUpload(ctx context.Context, in *InitMultiPartRequest, opts ...grpc.CallOption) (*InitMultiPartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitMultiPartResponse)
	err := c.cc.Invoke(ctx, S3_InitMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) AbortMultipartUpload(ctx context.Context, in *AbortMultipartRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_AbortMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartRequest, opts ...grpc.CallOption) (*CompleteMultipartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteMultipartResponse)
	err := c.cc.Invoke(ctx, S3_CompleteMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) UploadPart(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutDataStream, UploadPartResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &S3_ServiceDesc.Streams[2], S3_UploadPart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutDataStream, UploadPartResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S3_UploadPartClient = grpc.ClientStreamingClient[PutDataStream, UploadPartResponse]

func (c *s3Client) ListObjectParts(ctx context.Context, in *ListObjectPartsRequest, opts ...grpc.CallOption) (*ListObjectPartsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectPartsResponse)
	err := c.cc.Invoke(ctx, S3_ListObjectParts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) AppendObject(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_AppendObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) PostObject(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_PostObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) AddUploadRecord(ctx context.Context, in *MultipartUploadRecord, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_AddUploadRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) DeleteUploadRecord(ctx context.Context, in *MultipartUploadRecord, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_DeleteUploadRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) HeadObject(ctx context.Context, in *BaseObjRequest, opts ...grpc.CallOption) (*Object, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Object)
	err := c.cc.Invoke(ctx, S3_HeadObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) MoveObject(ctx context.Context, in *MoveObjectRequest, opts ...grpc.CallOption) (*MoveObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveObjectResponse)
	err := c.cc.Invoke(ctx, S3_MoveObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) CopyObject(ctx context.Context, in *CopyObjectRequest, opts ...grpc.CallOption) (*CopyObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyObjectResponse)
	err := c.cc.Invoke(ctx, S3_CopyObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) CopyObjPart(ctx context.Context, in *CopyObjPartRequest, opts ...grpc.CallOption) (*CopyObjPartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyObjPartResponse)
	err := c.cc.Invoke(ctx, S3_CopyObjPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) PutObjACL(ctx context.Context, in *PutObjACLRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_PutObjACL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetObjACL(ctx context.Context, in *BaseObjRequest, opts ...grpc.CallOption) (*ObjACL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjACL)
	err := c.cc.Invoke(ctx, S3_GetObjACL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetBucketLocation(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_GetBucketLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetBucketVersioning(ctx context.Context, in *BaseBucketRequest, opts ...grpc.CallOption) (*BucketVersioning, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BucketVersioning)
	err := c.cc.Invoke(ctx, S3_GetBucketVersioning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) PutBucketACL(ctx context.Context, in *PutBucketACLRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_PutBucketACL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetBucketACL(ctx context.Context, in *BaseBucketRequest, opts ...grpc.CallOption) (*BucketACL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BucketACL)
	err := c.cc.Invoke(ctx, S3_GetBucketACL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) PutBucketCORS(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_PutBucketCORS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetBucketCORS(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_GetBucketCORS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) DeleteBucketCORS(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_DeleteBucketCORS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) PutBucketPolicy(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_PutBucketPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) GetBucketPolicy(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_GetBucketPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) DeleteBucketPolicy(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_DeleteBucketPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) HeadBucket(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*Bucket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bucket)
	err := c.cc.Invoke(ctx, S3_HeadBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) RestoreObject(ctx context.Context, in *RestoreObjectRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_RestoreObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *s3Client) BackendCheck(ctx context.Context, in *BackendDetailS3, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, S3_BackendCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// S3Server is the server API for S3 service.
// All implementations must embed UnimplementedS3Server
// for forward compatibility.
type S3Server interface {
	ListBuckets(context.Context, *ListBucketsRequest) (*ListBucketsResponse, error)
	CreateBucket(context.Context, *Bucket) (*Bucket, error)
	DeleteBucket(context.Context, *Bucket) (*BaseResponse, error)
	GetBucket(context.Context, *Bucket) (*GetBucketResponse, error)
	GetObjectMeta(context.Context, *GetObjectMetaRequest) (*GetObjectMetaResult, error)
	UpdateObjectMeta(context.Context, *Object) (*PutObjectResponse, error)
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	CountObjects(context.Context, *ListObjectsRequest) (*CountObjectsResponse, error)
	PutObject(grpc.ClientStreamingServer[PutDataStream, PutObjectResponse]) error
	UpdateObject(context.Context, *Object) (*BaseResponse, error)
	GetObject(*GetObjectInput, grpc.ServerStreamingServer[GetObjectResponse]) error
	DeleteObject(context.Context, *DeleteObjectInput) (*DeleteObjectOutput, error)
	GetTierMap(context.Context, *BaseRequest) (*GetTierMapResponse, error)
	UpdateObjMeta(context.Context, *UpdateObjMetaRequest) (*BaseResponse, error)
	GetStorageClasses(context.Context, *BaseRequest) (*GetStorageClassesResponse, error)
	GetBackendTypeByTier(context.Context, *GetBackendTypeByTierRequest) (*GetBackendTypeByTierResponse, error)
	DeleteBucketLifecycle(context.Context, *BaseRequest) (*BaseResponse, error)
	PutBucketLifecycle(context.Context, *PutBucketLifecycleRequest) (*BaseResponse, error)
	GetBucketLifecycle(context.Context, *BaseRequest) (*GetBucketLifecycleResponse, error)
	ListBucketLifecycle(context.Context, *BaseRequest) (*ListBucketsResponse, error)
	UpdateBucket(context.Context, *Bucket) (*BaseResponse, error)
	ListBucketUploadRecords(context.Context, *ListBucketUploadRequest) (*ListBucketUploadResponse, error)
	InitMultipartUpload(context.Context, *InitMultiPartRequest) (*InitMultiPartResponse, error)
	AbortMultipartUpload(context.Context, *AbortMultipartRequest) (*BaseResponse, error)
	CompleteMultipartUpload(context.Context, *CompleteMultipartRequest) (*CompleteMultipartResponse, error)
	UploadPart(grpc.ClientStreamingServer[PutDataStream, UploadPartResponse]) error
	ListObjectParts(context.Context, *ListObjectPartsRequest) (*ListObjectPartsResponse, error)
	AppendObject(context.Context, *BaseRequest) (*BaseResponse, error)
	PostObject(context.Context, *BaseRequest) (*BaseResponse, error)
	// For lifecycle, may need some change.
	AddUploadRecord(context.Context, *MultipartUploadRecord) (*BaseResponse, error)
	DeleteUploadRecord(context.Context, *MultipartUploadRecord) (*BaseResponse, error)
	HeadObject(context.Context, *BaseObjRequest) (*Object, error)
	MoveObject(context.Context, *MoveObjectRequest) (*MoveObjectResponse, error)
	CopyObject(context.Context, *CopyObjectRequest) (*CopyObjectResponse, error)
	CopyObjPart(context.Context, *CopyObjPartRequest) (*CopyObjPartResponse, error)
	PutObjACL(context.Context, *PutObjACLRequest) (*BaseResponse, error)
	GetObjACL(context.Context, *BaseObjRequest) (*ObjACL, error)
	GetBucketLocation(context.Context, *BaseRequest) (*BaseResponse, error)
	GetBucketVersioning(context.Context, *BaseBucketRequest) (*BucketVersioning, error)
	PutBucketACL(context.Context, *PutBucketACLRequest) (*BaseResponse, error)
	GetBucketACL(context.Context, *BaseBucketRequest) (*BucketACL, error)
	PutBucketCORS(context.Context, *BaseRequest) (*BaseResponse, error)
	GetBucketCORS(context.Context, *BaseRequest) (*BaseResponse, error)
	DeleteBucketCORS(context.Context, *BaseRequest) (*BaseResponse, error)
	PutBucketPolicy(context.Context, *BaseRequest) (*BaseResponse, error)
	GetBucketPolicy(context.Context, *BaseRequest) (*BaseResponse, error)
	DeleteBucketPolicy(context.Context, *BaseRequest) (*BaseResponse, error)
	HeadBucket(context.Context, *BaseRequest) (*Bucket, error)
	RestoreObject(context.Context, *RestoreObjectRequest) (*BaseResponse, error)
	BackendCheck(context.Context, *BackendDetailS3) (*BaseResponse, error)
	mustEmbedUnimplementedS3Server()
}

// UnimplementedS3Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedS3Server struct{}

func (UnimplementedS3Server) ListBuckets(context.Context, *ListBucketsRequest) (*ListBucketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBuckets not implemented")
}
func (UnimplementedS3Server) CreateBucket(context.Context, *Bucket) (*Bucket, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBucket not implemented")
}
func (UnimplementedS3Server) DeleteBucket(context.Context, *Bucket) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBucket not implemented")
}
func (UnimplementedS3Server) GetBucket(context.Context, *Bucket) (*GetBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucket not implemented")
}
func (UnimplementedS3Server) GetObjectMeta(context.Context, *GetObjectMetaRequest) (*GetObjectMetaResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectMeta not implemented")
}
func (UnimplementedS3Server) UpdateObjectMeta(context.Context, *Object) (*PutObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateObjectMeta not implemented")
}
func (UnimplementedS3Server) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedS3Server) CountObjects(context.Context, *ListObjectsRequest) (*CountObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountObjects not implemented")
}
func (UnimplementedS3Server) PutObject(grpc.ClientStreamingServer[PutDataStream, PutObjectResponse]) error {
	return status.Error(codes.Unimplemented, "method PutObject not implemented")
}
func (UnimplementedS3Server) UpdateObject(context.Context, *Object) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateObject not implemented")
}
func (UnimplementedS3Server) GetObject(*GetObjectInput, grpc.ServerStreamingServer[GetObjectResponse]) error {
	return status.Error(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedS3Server) DeleteObject(context.Context, *DeleteObjectInput) (*DeleteObjectOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedS3Server) GetTierMap(context.Context, *BaseRequest) (*GetTierMapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTierMap not implemented")
}
func (UnimplementedS3Server) UpdateObjMeta(context.Context, *UpdateObjMetaRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateObjMeta not implemented")
}
func (UnimplementedS3Server) GetStorageClasses(context.Context, *BaseRequest) (*GetStorageClassesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorageClasses not implemented")
}
func (UnimplementedS3Server) GetBackendTypeByTier(context.Context, *GetBackendTypeByTierRequest) (*GetBackendTypeByTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBackendTypeByTier not implemented")
}
func (UnimplementedS3Server) DeleteBucketLifecycle(context.Context, *BaseRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBucketLifecycle not implemented")
}
func (UnimplementedS3Server) PutBucketLifecycle(context.Context, *PutBucketLifecycleRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutBucketLifecycle not implemented")
}
func (UnimplementedS3Server) GetBucketLifecycle(context.Context, *BaseRequest) (*GetBucketLifecycleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucketLifecycle not implemented")
}
func (UnimplementedS3Server) ListBucketLifecycle(context.Context, *BaseRequest) (*ListBucketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBucketLifecycle not implemented")
}
func (UnimplementedS3Server) UpdateBucket(context.Context, *Bucket) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBucket not implemented")
}
func (UnimplementedS3Server) ListBucketUploadRecords(context.Context, *ListBucketUploadRequest) (*ListBucketUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBucketUploadRecords not implemented")
}
func (UnimplementedS3Server) InitMultipartUpload(context.Context, *InitMultiPartRequest) (*InitMultiPartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitMultipartUpload not implemented")
}
func (UnimplementedS3Server) AbortMultipartUpload(context.Context, *AbortMultipartRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortMultipartUpload not implemented")
}
func (UnimplementedS3Server) CompleteMultipartUpload(context.Context, *CompleteMultipartRequest) (*CompleteMultipartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteMultipartUpload not implemented")
}
func (UnimplementedS3Server) UploadPart(grpc.ClientStreamingServer[PutDataStream, UploadPartResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadPart not implemented")
}
func (UnimplementedS3Server) ListObjectParts(context.Context, *ListObjectPartsRequest) (*ListObjectPartsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListObjectParts not implemented")
}
func (UnimplementedS3Server) AppendObject(context.Context, *BaseRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendObject not implemented")
}
func (UnimplementedS3Server) PostObject(context.Context, *BaseRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostObject not implemented")
}
func (UnimplementedS3Server) AddUploadRecord(context.Context, *MultipartUploadRecord) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUploadRecord not implemented")
}
func (UnimplementedS3Server) DeleteUploadRecord(context.Context, *MultipartUploadRecord) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUploadRecord not implemented")
}
func (UnimplementedS3Server) HeadObject(context.Context, *BaseObjRequest) (*Object, error) {
	return nil, status.Error(codes.Unimplemented, "method HeadObject not implemented")
}
func (UnimplementedS3Server) MoveObject(context.Context, *MoveObjectRequest) (*MoveObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveObject not implemented")
}
func (UnimplementedS3Server) CopyObject(context.Context, *CopyObjectRequest) (*CopyObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyObject not implemented")
}
func (UnimplementedS3Server) CopyObjPart(context.Context, *CopyObjPartRequest) (*CopyObjPartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyObjPart not implemented")
}
func (UnimplementedS3Server) PutObjACL(context.Context, *PutObjACLRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutObjACL not implemented")
}
func (UnimplementedS3Server) GetObjACL(context.Context, *BaseObjRequest) (*ObjACL, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjACL not implemented")
}
func (UnimplementedS3Server) GetBucketLocation(context.Context, *BaseRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucketLocation not implemented")
}
func (UnimplementedS3Server) GetBucketVersioning(context.Context, *BaseBucketRequest) (*BucketVersioning, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucketVersioning not implemented")
}
func (UnimplementedS3Server) PutBucketACL(context.Context, *PutBucketACLRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutBucketACL not implemented")
}
func (UnimplementedS3Server) GetBucketACL(context.Context, *BaseBucketRequest) (*BucketACL, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucketACL not implemented")
}
func (UnimplementedS3Server) PutBucketCORS(context.Context, *BaseRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutBucketCORS not implemented")
}
func (UnimplementedS3Server) GetBucketCORS(context.Context, *BaseRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucketCORS not implemented")
}
func (UnimplementedS3Server) DeleteBucketCORS(context.Context, *BaseRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBucketCORS not implemented")
}
func (UnimplementedS3Server) PutBucketPolicy(context.Context, *BaseRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutBucketPolicy not implemented")
}
func (UnimplementedS3Server) GetBucketPolicy(context.Context, *BaseRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucketPolicy not implemented")
}
func (UnimplementedS3Server) DeleteBucketPolicy(context.Context, *BaseRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBucketPolicy not implemented")
}
func (UnimplementedS3Server) HeadBucket(context.Context, *BaseRequest) (*Bucket, error) {
	return nil, status.Error(codes.Unimplemented, "method HeadBucket not implemented")
}
func (UnimplementedS3Server) RestoreObject(context.Context, *RestoreObjectRequest) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreObject not implemented")
}
func (UnimplementedS3Server) BackendCheck(context.Context, *BackendDetailS3) (*BaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BackendCheck not implemented")
}
func (UnimplementedS3Server) mustEmbedUnimplementedS3Server() {}
func (UnimplementedS3Server) testEmbeddedByValue()            {}

// UnsafeS3Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to S3Server will
// result in compilation errors.
type UnsafeS3Server interface {
	mustEmbedUnimplementedS3Server()
}

func RegisterS3Server(s grpc.ServiceRegistrar, srv S3Server) {
	// If the following call panics, it indicates UnimplementedS3Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&S3_ServiceDesc, srv)
}

func _S3_ListBuckets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBucketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).ListBuckets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_ListBuckets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).ListBuckets(ctx, req.(*ListBucketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_CreateBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).CreateBucket(ctx, req.(*Bucket))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_DeleteBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).DeleteBucket(ctx, req.(*Bucket))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetBucket(ctx, req.(*Bucket))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetObjectMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetObjectMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetObjectMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetObjectMeta(ctx, req.(*GetObjectMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_UpdateObjectMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).UpdateObjectMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_UpdateObjectMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).UpdateObjectMeta(ctx, req.(*Object))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_CountObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).CountObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_CountObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).CountObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_PutObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(S3Server).PutObject(&grpc.GenericServerStream[PutDataStream, PutObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S3_PutObjectServer = grpc.ClientStreamingServer[PutDataStream, PutObjectResponse]

func _S3_UpdateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).UpdateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_UpdateObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).UpdateObject(ctx, req.(*Object))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(S3Server).GetObject(m, &grpc.GenericServerStream[GetObjectInput, GetObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S3_GetObjectServer = grpc.ServerStreamingServer[GetObjectResponse]

func _S3_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).DeleteObject(ctx, req.(*DeleteObjectInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetTierMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetTierMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetTierMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetTierMap(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_UpdateObjMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateObjMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).UpdateObjMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_UpdateObjMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).UpdateObjMeta(ctx, req.(*UpdateObjMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetStorageClasses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetStorageClasses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetStorageClasses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetStorageClasses(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetBackendTypeByTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackendTypeByTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetBackendTypeByTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetBackendTypeByTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetBackendTypeByTier(ctx, req.(*GetBackendTypeByTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_DeleteBucketLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).DeleteBucketLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_DeleteBucketLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).DeleteBucketLifecycle(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_PutBucketLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutBucketLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).PutBucketLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_PutBucketLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).PutBucketLifecycle(ctx, req.(*PutBucketLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetBucketLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetBucketLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetBucketLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetBucketLifecycle(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_ListBucketLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).ListBucketLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_ListBucketLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).ListBucketLifecycle(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_UpdateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).UpdateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_UpdateBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).UpdateBucket(ctx, req.(*Bucket))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_ListBucketUploadRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBucketUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).ListBucketUploadRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_ListBucketUploadRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).ListBucketUploadRecords(ctx, req.(*ListBucketUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_InitMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitMultiPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).InitMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_InitMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).InitMultipartUpload(ctx, req.(*InitMultiPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_AbortMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortMultipartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).AbortMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_AbortMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).AbortMultipartUpload(ctx, req.(*AbortMultipartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_CompleteMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteMultipartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).CompleteMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_CompleteMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).CompleteMultipartUpload(ctx, req.(*CompleteMultipartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_UploadPart_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(S3Server).UploadPart(&grpc.GenericServerStream[PutDataStream, UploadPartResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type S3_UploadPartServer = grpc.ClientStreamingServer[PutDataStream, UploadPartResponse]

func _S3_ListObjectParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectPartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).ListObjectParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_ListObjectParts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).ListObjectParts(ctx, req.(*ListObjectPartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_AppendObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).AppendObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_AppendObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).AppendObject(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_PostObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).PostObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_PostObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).PostObject(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_AddUploadRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultipartUploadRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).AddUploadRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_AddUploadRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).AddUploadRecord(ctx, req.(*MultipartUploadRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_DeleteUploadRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultipartUploadRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).DeleteUploadRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_DeleteUploadRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).DeleteUploadRecord(ctx, req.(*MultipartUploadRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_HeadObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseObjRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).HeadObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_HeadObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).HeadObject(ctx, req.(*BaseObjRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_MoveObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).MoveObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_MoveObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).MoveObject(ctx, req.(*MoveObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_CopyObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).CopyObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_CopyObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).CopyObject(ctx, req.(*CopyObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_CopyObjPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyObjPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).CopyObjPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_CopyObjPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).CopyObjPart(ctx, req.(*CopyObjPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_PutObjACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutObjACLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).PutObjACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_PutObjACL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).PutObjACL(ctx, req.(*PutObjACLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetObjACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseObjRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetObjACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetObjACL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetObjACL(ctx, req.(*BaseObjRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetBucketLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetBucketLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetBucketLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetBucketLocation(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetBucketVersioning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetBucketVersioning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetBucketVersioning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetBucketVersioning(ctx, req.(*BaseBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_PutBucketACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutBucketACLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).PutBucketACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_PutBucketACL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).PutBucketACL(ctx, req.(*PutBucketACLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetBucketACL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetBucketACL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetBucketACL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetBucketACL(ctx, req.(*BaseBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_PutBucketCORS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).PutBucketCORS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_PutBucketCORS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).PutBucketCORS(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetBucketCORS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetBucketCORS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetBucketCORS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetBucketCORS(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_DeleteBucketCORS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).DeleteBucketCORS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_DeleteBucketCORS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).DeleteBucketCORS(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_PutBucketPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).PutBucketPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_PutBucketPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).PutBucketPolicy(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_GetBucketPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).GetBucketPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_GetBucketPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).GetBucketPolicy(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_DeleteBucketPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).DeleteBucketPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_DeleteBucketPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).DeleteBucketPolicy(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_HeadBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).HeadBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_HeadBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).HeadBucket(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_RestoreObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).RestoreObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_RestoreObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).RestoreObject(ctx, req.(*RestoreObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _S3_BackendCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackendDetailS3)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3Server).BackendCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3_BackendCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3Server).BackendCheck(ctx, req.(*BackendDetailS3))
	}
	return interceptor(ctx, in, info, handler)
}

// S3_ServiceDesc is the grpc.ServiceDesc for S3 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var S3_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "S3",
	HandlerType: (*S3Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBuckets",
			Handler:    _S3_ListBuckets_Handler,
		},
		{
			MethodName: "CreateBucket",
			Handler:    _S3_CreateBucket_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _S3_DeleteBucket_Handler,
		},
		{
			MethodName: "GetBucket",
			Handler:    _S3_GetBucket_Handler,
		},
		{
			MethodName: "GetObjectMeta",
			Handler:    _S3_GetObjectMeta_Handler,
		},
		{
			MethodName: "UpdateObjectMeta",
			Handler:    _S3_UpdateObjectMeta_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _S3_ListObjects_Handler,
		},
		{
			MethodName: "CountObjects",
			Handler:    _S3_CountObjects_Handler,
		},
		{
			MethodName: "UpdateObject",
			Handler:    _S3_UpdateObject_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _S3_DeleteObject_Handler,
		},
		{
			MethodName: "GetTierMap",
			Handler:    _S3_GetTierMap_Handler,
		},
		{
			MethodName: "UpdateObjMeta",
			Handler:    _S3_UpdateObjMeta_Handler,
		},
		{
			MethodName: "GetStorageClasses",
			Handler:    _S3_GetStorageClasses_Handler,
		},
		{
			MethodName: "GetBackendTypeByTier",
			Handler:    _S3_GetBackendTypeByTier_Handler,
		},
		{
			MethodName: "DeleteBucketLifecycle",
			Handler:    _S3_DeleteBucketLifecycle_Handler,
		},
		{
			MethodName: "PutBucketLifecycle",
			Handler:    _S3_PutBucketLifecycle_Handler,
		},
		{
			MethodName: "GetBucketLifecycle",
			Handler:    _S3_GetBucketLifecycle_Handler,
		},
		{
			MethodName: "ListBucketLifecycle",
			Handler:    _S3_ListBucketLifecycle_Handler,
		},
		{
			MethodName: "UpdateBucket",
			Handler:    _S3_UpdateBucket_Handler,
		},
		{
			MethodName: "ListBucketUploadRecords",
			Handler:    _S3_ListBucketUploadRecords_Handler,
		},
		{
			MethodName: "InitMultipartUpload",
			Handler:    _S3_InitMultipartUpload_Handler,
		},
		{
			MethodName: "AbortMultipartUpload",
			Handler:    _S3_AbortMultipartUpload_Handler,
		},
		{
			MethodName: "CompleteMultipartUpload",
			Handler:    _S3_CompleteMultipartUpload_Handler,
		},
		{
			MethodName: "ListObjectParts",
			Handler:    _S3_ListObjectParts_Handler,
		},
		{
			MethodName: "AppendObject",
			Handler:    _S3_AppendObject_Handler,
		},
		{
			MethodName: "PostObject",
			Handler:    _S3_PostObject_Handler,
		},
		{
			MethodName: "AddUploadRecord",
			Handler:    _S3_AddUploadRecord_Handler,
		},
		{
			MethodName: "DeleteUploadRecord",
			Handler:    _S3_DeleteUploadRecord_Handler,
		},
		{
			MethodName: "HeadObject",
			Handler:    _S3_HeadObject_Handler,
		},
		{
			MethodName: "MoveObject",
			Handler:    _S3_MoveObject_Handler,
		},
		{
			MethodName: "CopyObject",
			Handler:    _S3_CopyObject_Handler,
		},
		{
			MethodName: "CopyObjPart",
			Handler:    _S3_CopyObjPart_Handler,
		},
		{
			MethodName: "PutObjACL",
			Handler:    _S3_PutObjACL_Handler,
		},
		{
			MethodName: "GetObjACL",
			Handler:    _S3_GetObjACL_Handler,
		},
		{
			MethodName: "GetBucketLocation",
			Handler:    _S3_GetBucketLocation_Handler,
		},
		{
			MethodName: "GetBucketVersioning",
			Handler:    _S3_GetBucketVersioning_Handler,
		},
		{
			MethodName: "PutBucketACL",
			Handler:    _S3_PutBucketACL_Handler,
		},
		{
			MethodName: "GetBucketACL",
			Handler:    _S3_GetBucketACL_Handler,
		},
		{
			MethodName: "PutBucketCORS",
			Handler:    _S3_PutBucketCORS_Handler,
		},
		{
			MethodName: "GetBucketCORS",
			Handler:    _S3_GetBucketCORS_Handler,
		},
		{
			MethodName: "DeleteBucketCORS",
			Handler:    _S3_DeleteBucketCORS_Handler,
		},
		{
			MethodName: "PutBucketPolicy",
			Handler:    _S3_PutBucketPolicy_Handler,
		},
		{
			MethodName: "GetBucketPolicy",
			Handler:    _S3_GetBucketPolicy_Handler,
		},
		{
			MethodName: "DeleteBucketPolicy",
			Handler:    _S3_DeleteBucketPolicy_Handler,
		},
		{
			MethodName: "HeadBucket",
			Handler:    _S3_HeadBucket_Handler,
		},
		{
			MethodName: "RestoreObject",
			Handler:    _S3_RestoreObject_Handler,
		},
		{
			MethodName: "BackendCheck",
			Handler:    _S3_BackendCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutObject",
			Handler:       _S3_PutObject_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetObject",
			Handler:       _S3_GetObject_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadPart",
			Handler:       _S3_UploadPart_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "s3.proto",
}
